import streamlit as st

st.title("Serba serbi Jurusan TKJ")

st.write("Selamat datang di Chatbot Jurusan Teknik Komputer dan Jaringan (TKJ)!")

user_input = st.text_input("Anda:", "")

responses = {
    "apa itu tkj": "TKJ adalah singkatan dari Teknik Komputer dan Jaringan, jurusan yang mempelajari komputer, jaringan, dan teknologi informasi.",
    "prospek kerja tkj": "Lulusan TKJ dapat bekerja sebagai teknisi jaringan, administrator jaringan, IT support, dan masih banyak lagi.",
    "materi tkj": "Materi TKJ meliputi jaringan komputer, perangkat keras, perangkat lunak, pemrograman dasar, dan keamanan jaringan.",
    "kenapa pilih tkj": "TKJ cocok untuk kamu yang suka teknologi, komputer, dan ingin berkarir di bidang IT.",
    "keluar": "Terima kasih sudah menggunakan Chatbot TKJ!",
    "apa saja perangkat jaringan": "Perangkat jaringan meliputi router, switch, hub, access point, kabel jaringan, dan modem.",
    "apa itu ip address": "IP Address adalah alamat unik yang digunakan untuk mengidentifikasi perangkat dalam jaringan komputer.",
    "apa itu subnetting": "Subnetting adalah teknik membagi jaringan menjadi beberapa sub-jaringan agar lebih efisien dan aman.",
    "apa itu topologi jaringan": "Topologi jaringan adalah bentuk atau struktur fisik dan logis dari sebuah jaringan komputer, seperti topologi bus, star, ring, dan mesh.",
    "apa itu firewall": "Firewall adalah sistem keamanan jaringan yang mengontrol lalu lintas data masuk dan keluar berdasarkan aturan tertentu.",
    "apa itu server": "Server adalah komputer yang menyediakan layanan untuk komputer lain dalam jaringan, seperti file server, web server, dan database server.",
    "apa itu kabel utp": "Kabel UTP (Unshielded Twisted Pair) adalah kabel yang sering digunakan untuk jaringan komputer, terutama pada LAN.",
    "apa itu lan": "LAN (Local Area Network) adalah jaringan komputer yang mencakup area lokal seperti sekolah, kantor, atau rumah.",
    "apa itu wan": "WAN (Wide Area Network) adalah jaringan komputer yang mencakup area yang luas, seperti antar kota atau negara.",
    "apa itu protokol jaringan": "Protokol jaringan adalah aturan atau standar yang digunakan untuk komunikasi antar perangkat dalam jaringan, contohnya TCP/IP.",
    "apa itu dns": "DNS (Domain Name System) adalah sistem yang mengubah nama domain menjadi IP address agar mudah diakses.",
    "apa itu vpn": "VPN (Virtual Private Network) adalah teknologi yang memungkinkan koneksi aman melalui jaringan publik seperti internet.",
    "apa itu troubleshooting jaringan": "Troubleshooting jaringan adalah proses mencari dan memperbaiki masalah yang terjadi pada jaringan komputer.",
    "apa itu bandwidth": "Bandwidth adalah kapasitas maksimum data yang dapat dikirimkan melalui jaringan dalam waktu tertentu.",
    "apa itu wireless": "Wireless adalah teknologi jaringan tanpa kabel, seperti WiFi dan Bluetooth.",
    "apa itu ethernet": "Ethernet adalah teknologi jaringan kabel yang umum digunakan untuk LAN.",
    "apa itu switch": "Switch adalah perangkat jaringan yang menghubungkan beberapa perangkat dalam satu jaringan dan mengirimkan data hanya ke perangkat tujuan.",
    "apa itu router": "Router adalah perangkat yang menghubungkan dua atau lebih jaringan dan meneruskan data antar jaringan tersebut.",
    "apa itu modem": "Modem adalah perangkat yang mengubah sinyal digital menjadi analog dan sebaliknya, biasanya digunakan untuk koneksi internet.",
    "apa itu access point": "Access Point adalah perangkat yang memungkinkan perangkat wireless terhubung ke jaringan kabel.",
    "apa itu repeater": "Repeater adalah perangkat yang memperkuat sinyal jaringan agar dapat menjangkau area yang lebih luas.",
    "apa itu bridge": "Bridge adalah perangkat yang menghubungkan dua jaringan lokal agar dapat berkomunikasi.",
    "apa itu hub": "Hub adalah perangkat jaringan yang menghubungkan beberapa komputer dalam satu jaringan, namun data dikirim ke semua perangkat.",
    "apa itu network card": "Network card atau NIC adalah perangkat keras yang memungkinkan komputer terhubung ke jaringan.",
    "apa itu ping": "Ping adalah perintah untuk menguji koneksi antara dua perangkat dalam jaringan.",
    "apa itu proxy": "Proxy adalah server yang menjadi perantara antara pengguna dan internet untuk meningkatkan keamanan dan privasi.",
    "apa itu port": "Port adalah titik akses logis untuk komunikasi data pada komputer atau perangkat jaringan.",
    "apa itu mac address": "MAC Address adalah alamat fisik unik yang dimiliki setiap perangkat jaringan.",
    "apa itu dhcp": "DHCP (Dynamic Host Configuration Protocol) adalah protokol yang secara otomatis memberikan IP address ke perangkat dalam jaringan.",
    "apa itu ftp": "FTP (File Transfer Protocol) adalah protokol untuk transfer file antara komputer melalui jaringan.",
    "apa itu ssh": "SSH (Secure Shell) adalah protokol untuk komunikasi aman antara dua perangkat dalam jaringan.",
    "apa itu web server": "Web server adalah server yang menyimpan dan mengirimkan halaman web ke pengguna melalui internet.",
    "apa itu database server": "Database server adalah server yang menyimpan dan mengelola data dalam bentuk database.",
    "apa itu cloud computing": "Cloud computing adalah teknologi yang memungkinkan penyimpanan dan pengolahan data melalui internet.",
    "apa itu virtualisasi": "Virtualisasi adalah teknologi yang memungkinkan satu perangkat keras menjalankan beberapa sistem operasi secara bersamaan.",
    "apa itu backup": "Backup adalah proses membuat salinan data untuk mencegah kehilangan data.",
    "apa itu restore": "Restore adalah proses mengembalikan data dari backup ke kondisi semula.",
    "apa itu malware": "Malware adalah perangkat lunak berbahaya yang dapat merusak atau mencuri data dari komputer.",
    "apa itu antivirus": "Antivirus adalah perangkat lunak yang digunakan untuk mendeteksi dan menghapus malware dari komputer.",
    "apa itu trojan": "Trojan adalah jenis malware yang menyamar sebagai program biasa untuk mencuri data atau merusak sistem.",
    "apa itu worm": "Worm adalah malware yang dapat menyebar sendiri ke komputer lain melalui jaringan.",
    "apa itu phishing": "Phishing adalah upaya penipuan untuk mendapatkan data pribadi dengan menyamar sebagai pihak terpercaya.",
    "apa itu backup jaringan": "Backup jaringan adalah proses membuat salinan data dan konfigurasi jaringan untuk mencegah kehilangan data.",
    "apa itu keamanan jaringan": "Keamanan jaringan adalah upaya untuk melindungi jaringan dari ancaman dan serangan.",
    "apa itu enkripsi": "Enkripsi adalah proses mengubah data menjadi kode agar tidak bisa dibaca oleh pihak yang tidak berwenang.",
    "apa itu dekripsi": "Dekripsi adalah proses mengubah data terenkripsi kembali ke bentuk aslinya.",
    "apa itu peer to peer": "Peer to peer adalah model jaringan di mana setiap komputer dapat bertindak sebagai client maupun server.",
    "apa itu client server": "Client server adalah model jaringan di mana satu komputer bertindak sebagai server dan lainnya sebagai client.",
    "apa itu topologi star": "Topologi star adalah bentuk jaringan di mana semua perangkat terhubung ke satu pusat (hub atau switch).",
    "apa itu topologi bus": "Topologi bus adalah bentuk jaringan di mana semua perangkat terhubung ke satu kabel utama.",
    "apa itu topologi ring": "Topologi ring adalah bentuk jaringan di mana perangkat terhubung membentuk lingkaran.",
    "apa itu topologi mesh": "Topologi mesh adalah bentuk jaringan di mana setiap perangkat terhubung langsung ke perangkat lain.",
    "apa itu internet": "Internet adalah jaringan global yang menghubungkan jutaan komputer di seluruh dunia.",
    "apa itu intranet": "Intranet adalah jaringan lokal yang hanya dapat diakses oleh anggota organisasi tertentu.",
    "apa itu extranet": "Extranet adalah jaringan yang memungkinkan akses terbatas ke pihak luar organisasi.",
    "apa itu ssid": "SSID (Service Set Identifier) adalah nama jaringan wireless yang digunakan untuk mengidentifikasi jaringan WiFi.",
    "apa itu bluetooth": "Bluetooth adalah teknologi wireless untuk komunikasi jarak pendek antar perangkat.",
    "apa itu hotspot": "Hotspot adalah area di mana perangkat dapat terhubung ke internet melalui jaringan wireless.",
    "apa itu network topology": "Network topology adalah cara perangkat jaringan diatur dan terhubung satu sama lain.",
    "apa itu network security": "Network security adalah perlindungan jaringan dari akses tidak sah dan ancaman.",
    "apa itu packet": "Packet adalah unit data yang dikirimkan melalui jaringan.",
    "apa itu protocol": "Protocol adalah aturan komunikasi antar perangkat dalam jaringan.",
    "apa itu gateway": "Gateway adalah perangkat yang menghubungkan dua jaringan dengan protokol berbeda.",
    "apa itu NAT": "NAT (Network Address Translation) adalah teknik untuk mengubah alamat IP pada paket data agar dapat melewati router.",
    "apa itu VLAN": "VLAN (Virtual LAN) adalah jaringan virtual yang dibentuk dalam satu jaringan fisik untuk memisahkan trafik.",
    "apa itu RJ45": "RJ45 adalah konektor yang digunakan untuk kabel jaringan Ethernet.",
    "apa itu OSI Layer": "OSI Layer adalah model referensi yang membagi proses komunikasi jaringan menjadi 7 lapisan.",
    "apa itu TCP/IP": "TCP/IP adalah protokol utama yang digunakan untuk komunikasi data di internet dan jaringan komputer.",
    "apa itu ARP": "ARP (Address Resolution Protocol) adalah protokol untuk menemukan MAC address dari IP address.",
    "apa itu ICMP": "ICMP (Internet Control Message Protocol) adalah protokol untuk mengirim pesan kesalahan dan informasi di jaringan.",
    "apa itu UDP": "UDP (User Datagram Protocol) adalah protokol komunikasi yang tidak menjamin pengiriman data.",
    "apa itu TCP": "TCP (Transmission Control Protocol) adalah protokol komunikasi yang menjamin pengiriman data secara berurutan dan tanpa kehilangan.",
    "apa itu SSL": "SSL (Secure Sockets Layer) adalah protokol keamanan untuk komunikasi data melalui internet.",
    "apa itu HTTPS": "HTTPS adalah versi aman dari HTTP yang menggunakan SSL/TLS untuk enkripsi data.",
    "apa itu HTTP": "HTTP (Hypertext Transfer Protocol) adalah protokol untuk komunikasi data di web.",
    "apa itu SMTP": "SMTP (Simple Mail Transfer Protocol) adalah protokol untuk mengirim email.",
    "apa itu POP3": "POP3 (Post Office Protocol 3) adalah protokol untuk mengambil email dari server.",
    "apa itu IMAP": "IMAP (Internet Message Access Protocol) adalah protokol untuk mengakses email dari server.",
    "apa itu bandwidth": "Bandwidth adalah kapasitas maksimum data yang dapat dikirimkan melalui jaringan dalam waktu tertentu.",
    "apa itu latency": "Latency adalah waktu yang dibutuhkan data untuk berpindah dari satu titik ke titik lain dalam jaringan.",
    "apa itu jitter": "Jitter adalah variasi waktu pengiriman paket data dalam jaringan.",
    "apa itu packet loss": "Packet loss adalah hilangnya paket data selama transmisi dalam jaringan.",
    "apa itu QoS": "QoS (Quality of Service) adalah mekanisme untuk mengatur prioritas trafik dalam jaringan.",
    "apa itu load balancing": "Load balancing adalah teknik untuk membagi beban kerja secara merata di beberapa perangkat atau server.",
    "apa itu redundancy": "Redundancy adalah sistem cadangan untuk memastikan jaringan tetap berjalan jika terjadi kegagalan.",
    "apa itu failover": "Failover adalah proses otomatis beralih ke sistem cadangan saat sistem utama gagal.",
    "apa itu network monitoring": "Network monitoring adalah proses memantau kinerja dan keamanan jaringan.",
    "apa itu SNMP": "SNMP (Simple Network Management Protocol) adalah protokol untuk mengelola dan memantau perangkat jaringan.",
    "apa itu syslog": "Syslog adalah protokol untuk mengirim pesan log dari perangkat jaringan ke server log.",
    "apa itu patch panel": "Patch panel adalah perangkat untuk mengatur dan menghubungkan kabel jaringan di satu tempat.",
    "apa itu rack server": "Rack server adalah server yang dipasang di rak khusus untuk efisiensi ruang dan pengelolaan.",
    "apa itu colocation": "Colocation adalah layanan penempatan server di data center pihak ketiga.",
    "apa itu data center": "Data center adalah fasilitas untuk menyimpan, mengelola, dan mengamankan server dan data.",
    "apa itu uptime": "Uptime adalah waktu di mana sistem atau jaringan beroperasi tanpa gangguan.",
    "apa itu downtime": "Downtime adalah waktu di mana sistem atau jaringan tidak beroperasi karena gangguan.",
    "apa itu SLA": "SLA (Service Level Agreement) adalah perjanjian tingkat layanan antara penyedia dan pengguna layanan.",
    "apa itu ISP": "ISP (Internet Service Provider) adalah perusahaan yang menyediakan layanan akses internet.",
    "apa itu backbone": "Backbone adalah jalur utama yang menghubungkan berbagai jaringan dalam skala besar.",
    "apa itu peer": "Peer adalah perangkat atau komputer yang setara dalam jaringan peer to peer.",
    "apa itu client": "Client adalah perangkat yang meminta layanan dari server dalam jaringan.",
    "apa itu server farm": "Server farm adalah kumpulan server yang bekerja bersama untuk menyediakan layanan jaringan.",
    "apa itu clustering": "Clustering adalah teknik menggabungkan beberapa server untuk meningkatkan kinerja dan ketersediaan.",
    "apa itu remote access": "Remote access adalah kemampuan mengakses jaringan atau komputer dari lokasi jauh.",
    "apa itu remote desktop": "Remote desktop adalah teknologi untuk mengakses tampilan dan kontrol komputer dari jarak jauh.",
    "apa itu network management": "Network management adalah proses mengelola, memantau, dan mengoptimalkan jaringan.",
    "apa itu network engineer": "Network engineer adalah profesional yang merancang, mengelola, dan memelihara jaringan komputer.",
    "apa itu IT support": "IT support adalah layanan bantuan teknis untuk pengguna komputer dan jaringan.",
    "apa itu troubleshooting": "Troubleshooting adalah proses mencari dan memperbaiki masalah pada perangkat atau jaringan.",
    "apa itu upgrade jaringan": "Upgrade jaringan adalah proses meningkatkan kapasitas atau fitur jaringan.",
    "apa itu maintenance jaringan": "Maintenance jaringan adalah perawatan rutin untuk menjaga jaringan tetap berjalan optimal.",
    "apa itu konfigurasi jaringan": "Konfigurasi jaringan adalah pengaturan perangkat dan protokol agar jaringan berjalan sesuai kebutuhan.",
    "apa itu dokumentasi jaringan": "Dokumentasi jaringan adalah pencatatan konfigurasi, perangkat, dan topologi jaringan untuk referensi dan pemeliharaan.",
}

if user_input:
    key = user_input.lower()
    response = responses.get(key, "Maaf, saya hanya bisa menjawab seputar TKJ. Coba ketik: 'apa itu tkj', 'prospek kerja tkj', 'materi tkj', atau 'kenapa pilih tkj'.")
    st.write(f"Bot: {response}")
    if key == "keluar":
        st.stop()
